### ISSUE TITLE
openvpn logging

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/puppet#17]
Each openvpn instance should log to `/var/log/openvpn/` and we should add a logrotate file to `/etc/logrotate.d/` for openvpn.

**Comment by booo** [comment]
On vpn03a we now log to /var/log/openvpn/udp.log for the udp configuration. I created a logrotate configuration with daily/100M rotation. I going to add this to the tcp configuration as well and will add this to the puppet configuration for vpn03b/c.

**Comment by andrenarchy** [comment]
How long are the logs stored in total? Only one day?

**Comment by cholin** [comment]
Why consider logging at all? I thought we don't want to keep logs?

**Comment by andrenarchy** [comment]
For tracking down problems it may make sense to log for a short time. But we could activate logging if it's actually needed... If there are no problems I agree with @cholin: we shouldn't be logging at all.

**Comment by booo** [comment]
We log one day for now. If it is consensus I switch logging of. I would like to get feedback from @egmont1227 and @sven-ola too.

Do we need the status files? Can I move the status files to /var/log/ with breaking any scripts?

**Comment by booo** [comment]
I'm going to switch logging of at the end of the week.

**Comment by egmont1227** [comment]
i am fine with turn off logging.

**Comment by booo** [comment]
I switched of logging on vpn03a/b.
