### ISSUE TITLE
shutdown openvpn instance ianua-melle

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/puppet#23]
On the vpn03a host we have another openvpn instance apart from the tcp and udp instances. We should move all users to the new instance and shutdown the instance. I contacted possible useres with new credentials and asked them to migrate. I will shutdown the old instance at 2015-01-15.

**Comment by egmont1227** [comment]
whats the status here? any news from the users?

Whats the hurry for 15.1.15 ?

**Comment by booo** [comment]
All old users should have received new credentials and should use the new system by now. I going to shutdown the old instance next week. I don't see a reason why we should wait longer with a proper migration.

**Comment by booo** [comment]
I removed the instance from vpn03a after all users I know of migrated to the new setup.
