### ISSUE TITLE
improve the  base/standard package set for all hosts

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/puppet#26]
We already have a minimal package set for all hosts:

https://github.com/freifunk-berlin/puppet/blob/master/puppet/manifests/site.pp#L16

We should add some standard debugging tools such as:

* mtr
* tracepath
* tcpdump
* screen

@cholin you mentioned some other packages. Can you add them to the list?

**Comment by egmont1227** [comment]
* byobu
* htop

**Comment by booo** [comment]
I added the proposed packages. Please take a look at the code or ask we if you need another package.
