### ISSUE TITLE
create wsgi configuration for nipap-www

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/puppet#30]
At the moment nipap-www runs in a tmux instance. We should create a wsgi configuration for nipap-www. Nipap-www is the admin interface for nipap. Nipap-www should listen on localhost.

https://github.com/SpriteLink/NIPAP/blob/master/nipap-www/nipap-www.wsgi

**Comment by pmelange** [comment]
https://github.com/freifunk-berlin/puppet-uwsgi exists.  Closing
