### ISSUE TITLE
fix https for download.berlin.freifunk.net

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/puppet#44]
https for https://download.berlin.freifunk.net/ is broken. We should fix this.

**Comment by booo** [comment]
@nosy79 will try to contact 176.28.11.93 about https configuration.

**Comment by nosy79** [comment]
download.berlin.freifunk.net uses an invalid security certificate. The certificate is only valid for the following names: api-viewer.freifunk.net, freifunk.net

**Comment by pmelange** [comment]
Setup currently uses LetsEncrypt.  Fixed on or before #66
