### ISSUE TITLE
update config to use LetsEncrypt

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/puppet#48]
Most of the certificates are valid till November. We should update the certificates.

**Comment by SvenRoederer** [comment]
... and renewal timed out ....

@sarumpaet spoke on cronjobs for LetsEncrypt

**Comment by sarumpaet** [comment]
Certs have been updated (using LE) but the Puppet config still needs updating.
* cert paths
* certbot client
* renewal cronjob
* access to `/.well-known/`
* (get setup - `/etc/letsencrypt` - from backup)

**Comment by pmelange** [comment]
Fixed on or before #66
