### ISSUE TITLE
Readme SSL

### ISSUE THREAD

**Issue by SvenSFS** [freifunk-berlin/puppet#54]
Da StartSSL ja nicht mehr Existent ist und bei vielen
Distributionen rausgeflogen ist sollte hier auf LE verweisen werden.
Auch die WIKI Seite solle geändert werden.

Sven

**Comment by booo** [comment]
Bitte einen konkreten Änderungsvorschlag machen, dann passen wir das an.

**Comment by SvenSFS** [comment]
Steht doch oben. Statt StartSSL sollte das gegen LE getauscht werden. 
Das ist nur ein Update der Informationen. Phillipp wasn los?

**Comment by pmelange** [comment]
The VM's have moved to LetsEncrypt. Closing...
