### ISSUE TITLE
buildbot.berlin: util script need to be installed.

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/puppet#69]
The script https://github.com/freifunk-berlin/util.berlin.freifunk.net/blob/master/www/hardware.php should be set up in a cronjob.  This script updates the firmware download pages on util.berlin.

**Comment by pmelange** [comment]
In the end, the script that runs on the server is
```
#!/bin/bash
PATH=/bin:/usr/bin
cd /usr/local/src/www/htdocs/buildbot
(find . -type f | cut -c 3- ; \
grep "Firmware: git branch" unstable/*/*/VERSION.txt ; \
find . -name "VERSION.txt" -printf "UNIXTIME %C@ %p\n" \
) | lzma > /usr/local/src/www/htdocs/buildbot/.files.lzma.new
mv /usr/local/src/www/htdocs/buildbot/.files.lzma.new /usr/local/src/www/htdocs/buildbot/.files.lzma
```

and maybe it makes more sense to integrade into the master script, so that it updates after each worker uploads their stuff.  This could also be put in combination with removing old devel builds.

**Comment by pmelange** [comment]
I set up this script, for now, in cron.hourly/buildbot-update-lists

**Comment by rtznprmpftl** [comment]
@pmelange  the cronjob right now is:
```

#!/bin/sh

BASE_DIR="/usr/local/src/www/htdocs/buildbot/unstable"
TARGETS=$(ls ${BASE_DIR})
for target in ${TARGETS}; do
  for build in $(ls -t "${BASE_DIR}/${target}" | tail -n +10); do
    rm -r "${BASE_DIR}/${target}/${build}"
  done
done

```

so i will  use this as a reference, instead what you wrote in the comment before, ok?

**Comment by rtznprmpftl** [comment]
added here: https://github.com/freifunk-berlin/ff_base/commit/e4b39f31d6e2f2a4ffbaee06aa1eed4aef01034c
