### ISSUE TITLE
monitor.berlin change setting $CONFIG['showload'] = false; greatly improves loadtime

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/puppet#71]
I have changed the value ```$CONFIG['showload']``` to false, and the loadtime for the landing page is a lot faster.

Filename: /srv/www/monitor.berlin.freifunk.net/conf/config.php

I would like to keep this setting.  It would also be really cool if it were added into puppet.

If anyone disagrees with this change, please let me know and I will change it back.

**Comment by booo** [comment]
Amazing! The config.php file is part of the puppet-files module. Can you prepare a change for this file? Maybe coordinate with @rtznprmpftl

**Comment by pmelange** [comment]
config.local.php is already in the repo, but config.php is not.  I tried setting config.php back to how it was, and added the setting to config.local.php and it didn't work.  

Maybe it is possible to set it in the puppet module.  
```
  # collectd configuration (server)
  class { '::collectd':
    purge        => true,
    recurse      => true,
    purge_config => true,
    typesdb      => [
      '/usr/share/collectd/types.db',
      '/usr/share/collectd/iwinfo_types.db',
      '/usr/share/collectd/kmodem_types.db'
    ]
  }
```
I really am not good at puppet and php. :/

**Comment by booo** [comment]
config.local.php should overwrite config.php.

**Comment by pmelange** [comment]
I thought too that config.local.php would override the settings in config.php.  But for some reason it didn't work.  Strange.  Any ideas why?

**Comment by pmelange** [comment]
WTF?  I just tried it again, and it worked.  OK.  I'll prepare a PR.

**Comment by pmelange** [comment]
see https://github.com/freifunk-berlin/puppet-files/pull/8

**Comment by booo** [comment]
Smoke weed everyday... NOT ;)
